### ISSUE TITLE
Keywords & License

### ISSUE THREAD

**Issue by SpiderMath** [Commandtechno/robert#1]
I would suggest adding some keywords into the package.json, since that would help NPM know what topic your package covers and would give it a higher rank in search results

Adding a License is suggested too, like a License file or something.

**Comment by Commandtechno** [comment]
added in 1.1.1! ty

if you have any suggestions though please tell me i just copied some random stuff

**Comment by SpiderMath** [comment]
What exactly do you mean by `copied some random stuff`?
Sounds waaay to ominous for me to ignore :cold_sweat:

**Comment by Commandtechno** [comment]
i just read my email and saw this and idk i think i just found it on a random repo and copied it and then pog
